package ups.g1.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-05T11:53:34.570-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.g1.ups/", name = "Servicios")
@XmlSeeAlso({ObjectFactory.class})
public interface Servicios {

    @WebMethod
    @RequestWrapper(localName = "numero", targetNamespace = "http://service.g1.ups/", className = "ups.g1.service.Numero")
    @ResponseWrapper(localName = "numeroResponse", targetNamespace = "http://service.g1.ups/", className = "ups.g1.service.NumeroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int numero();
}
