
package ups.g1.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-05T12:24:23.363-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class Servicios_ServiciosPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.g1.ups/", "ServiciosService");

    private Servicios_ServiciosPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiciosService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServiciosService ss = new ServiciosService(wsdlURL, SERVICE_NAME);
        Servicios port = ss.getServiciosPort();  
        
        {
        System.out.println("Invoking solicitud...");
        int _solicitud__return = port.solicitud();
        System.out.println("solicitud.result=" + _solicitud__return);


        }

        System.exit(0);
    }

}
