package ups.g1.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-02-05T12:24:23.492-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "ServiciosService", 
                  wsdlLocation = "file:/C:/Users/lilia/AppData/Local/Temp/tempdir2038575144348616301.tmp/Servicios_1.wsdl",
                  targetNamespace = "http://service.g1.ups/") 
public class ServiciosService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.g1.ups/", "ServiciosService");
    public final static QName ServiciosPort = new QName("http://service.g1.ups/", "ServiciosPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/lilia/AppData/Local/Temp/tempdir2038575144348616301.tmp/Servicios_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiciosService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/lilia/AppData/Local/Temp/tempdir2038575144348616301.tmp/Servicios_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiciosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiciosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiciosService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiciosService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiciosService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Servicios
     */
    @WebEndpoint(name = "ServiciosPort")
    public Servicios getServiciosPort() {
        return super.getPort(ServiciosPort, Servicios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Servicios
     */
    @WebEndpoint(name = "ServiciosPort")
    public Servicios getServiciosPort(WebServiceFeature... features) {
        return super.getPort(ServiciosPort, Servicios.class, features);
    }

}
